# CMake generated Testfile for 
# Source directory: /Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing
# Build directory: /Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(igtlMultiThreaderTest1 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMultiThreaderTest1")
set_tests_properties(igtlMultiThreaderTest1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;144;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMultiThreaderTest2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMultiThreaderTest2")
set_tests_properties(igtlMultiThreaderTest2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;145;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMultiThreaderTest3 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMultiThreaderTest3")
set_tests_properties(igtlMultiThreaderTest3 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;146;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMessageFactoryTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMessageFactoryTest")
set_tests_properties(igtlMessageFactoryTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;147;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTimeStampTest1 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTimeStampTest1")
set_tests_properties(igtlTimeStampTest1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;148;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMessageBaseTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMessageBaseTest")
set_tests_properties(igtlMessageBaseTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;149;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlConditionVariableTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlConditionVariableTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlConditionVariableTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;150;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlImageMessageTest")
set_tests_properties(igtlImageMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;152;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMessage2Test "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlImageMessage2Test")
set_tests_properties(igtlImageMessage2Test PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;153;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlCapabilityMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlCapabilityMessageTest")
set_tests_properties(igtlCapabilityMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;154;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlStatusMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlStatusMessageTest")
set_tests_properties(igtlStatusMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;155;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTransformMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTransformMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlTransformMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;156;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlPositionMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlPositionMessageTest")
set_tests_properties(igtlPositionMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;157;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlBindMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlBindMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlBindMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;162;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlColorTableMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlColorTableMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlColorTableMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;163;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlLabelMetaMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlLabelMetaMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;164;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlNDArrayMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlNDArrayMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlNDArrayMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;165;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMetaMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlImageMetaMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;166;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlPointMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlPointMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlPointMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;167;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlPolyDataMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlPolyDataMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlPolyDataMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;168;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlSensorMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlSensorMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlSensorMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;169;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlStringMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlStringMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlStringMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;170;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTrackingDataMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTrackingDataMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlTrackingDataMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;171;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTrajectoryMessageTest "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTrajectoryMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlTrajectoryMessageTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;172;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMessageBaseTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMessageBaseTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlMessageBaseTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;178;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlImageMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlImageMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;179;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMessage2TestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlImageMessage2Test" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlImageMessage2TestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;180;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlBindMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlBindMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlBindMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;181;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlCapabilityMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlCapabilityMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlCapabilityMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;182;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlColorTableMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlColorTableMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlColorTableMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;183;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlConditionVariableTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlConditionVariableTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlConditionVariableTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;184;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlLabelMetaMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlLabelMetaMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;185;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlNDArrayMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlNDArrayMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlNDArrayMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;186;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlImageMetaMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlImageMetaMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;187;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlPointMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlPointMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlPointMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;188;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlPolyDataMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlPolyDataMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlPolyDataMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;189;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlSensorMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlSensorMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlSensorMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;190;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlStatusMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlStatusMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlStatusMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;191;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlStringMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlStringMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlStringMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;192;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTrackingDataMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTrackingDataMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlTrackingDataMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;193;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTrajectoryMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTrajectoryMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlTrajectoryMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;194;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlTransformMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlTransformMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlTransformMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;195;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlCommandMessageTestFormatVersion1 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlCommandMessageTest" "--gtest_filter=*.*FormatVersion1")
set_tests_properties(igtlCommandMessageTestFormatVersion1 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;198;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlCommandMessageTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlCommandMessageTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlCommandMessageTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;199;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
add_test(igtlMessageRTPWrapperTestFormatVersion2 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtlMessageRTPWrapperTest" "--gtest_filter=*.*FormatVersion2")
set_tests_properties(igtlMessageRTPWrapperTestFormatVersion2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;200;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/CMakeLists.txt;0;")
subdirs("igtlutil")
subdirs("gmock-build")
