# CMake generated Testfile for 
# Source directory: /Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil
# Build directory: /Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/Testing/igtlutil
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(igtl_image_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_image_test")
set_tests_properties(igtl_image_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;45;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_header_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_header_test")
set_tests_properties(igtl_header_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;46;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_transform_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_transform_test")
set_tests_properties(igtl_transform_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;47;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_status_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_status_test")
set_tests_properties(igtl_status_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;48;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_util_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_util_test")
set_tests_properties(igtl_util_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;49;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_position_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_position_test")
set_tests_properties(igtl_position_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;50;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_capability_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_capability_test")
set_tests_properties(igtl_capability_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;51;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_colortable_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_colortable_test")
set_tests_properties(igtl_colortable_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;54;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_imgmeta_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_imgmeta_test")
set_tests_properties(igtl_imgmeta_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;55;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_lbmeta_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_lbmeta_test")
set_tests_properties(igtl_lbmeta_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;56;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_point_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_point_test")
set_tests_properties(igtl_point_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;57;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_tdata_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_tdata_test")
set_tests_properties(igtl_tdata_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;58;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_trajectory_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_trajectory_test")
set_tests_properties(igtl_trajectory_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;59;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_sensor_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_sensor_test")
set_tests_properties(igtl_sensor_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;60;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_string_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_string_test")
set_tests_properties(igtl_string_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;61;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_bind_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_bind_test")
set_tests_properties(igtl_bind_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;62;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_ndarray_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_ndarray_test")
set_tests_properties(igtl_ndarray_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;63;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
add_test(igtl_polydata_test_01 "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink-build/bin/igtl_polydata_test")
set_tests_properties(igtl_polydata_test_01 PROPERTIES  _BACKTRACE_TRIPLES "/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;64;ADD_TEST;/Users/lisa/Desktop/BRPRobot2021/SNR/OpenIGTLink/Testing/igtlutil/CMakeLists.txt;0;")
